AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  image_catalog

  Sample SAM Template for image_catalog

Parameters:
  BucketName:
    Type: String
    Default: daitawscloud-example

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  ImagesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  
  ImageCatalogFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ImagesTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          IMAGES_TABLE: !Ref ImagesTable
      Events:
        S3ObjectCreated:
          Type: S3
          Properties:
            Bucket:
              Ref: ImageBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: "png"

    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./imagecatalog
      Dockerfile: Dockerfile

Outputs:
  ImageCatalogFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ImageCatalogFunction.Arn
